version: '3'
services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: sk-ePPMBTIm0ajMsfpSOVKNT
      OPENAI_API_BASE_URL: https://api.openai.com
      AUTH_SECRET_KEY: masa
      OPENAI_API_MODEL: gpt-3.5-turbo
